import axios from "axios";
import { FIREBASE_DB_URL } from "./firebaseConfig";

// Favorites are stored in Firebase like this:
// favorites: {
//   <userId>: {
//     <mealId>: true,
//     <mealId>: true,
//   }
// }

export async function fetchFavorites(userId, token) {
  const response = await axios.get(
    `${FIREBASE_DB_URL}/favorites/${userId}.json?auth=${token}`
  );

  // response.data is either null (no favorites yet) or an object like { m1: true, m3: true }
  const favoritesObj = response.data || {};
  return Object.keys(favoritesObj); // -> ['m1', 'm3']
}

export function storeFavorite(userId, mealId, token) {
  return axios.put(
    `${FIREBASE_DB_URL}/favorites/${userId}/${mealId}.json?auth=${token}`,
    JSON.stringify(true),
    { headers: { "Content-Type": "application/json" } }
  );
}

export function deleteFavorite(userId, mealId, token) {
  return axios.delete(
    `${FIREBASE_DB_URL}/favorites/${userId}/${mealId}.json?auth=${token}`
  );
}

// Orders (cart) are stored in Firebase like this:
// orders: {
//   <userId>: {
//     <mealId>: <quantity>,
//     <mealId>: <quantity>,
//   }
// }

export async function fetchOrder(userId, token) {
  const response = await axios.get(
    `${FIREBASE_DB_URL}/orders/${userId}.json?auth=${token}`
  );

  // response.data is either null (no items yet) or an object like { m1: 2, m3: 1 }
  const orderObj = response.data || {};
  return Object.keys(orderObj).map((id) => ({
    id,
    quantity: orderObj[id],
  })); // -> [{ id: 'm1', quantity: 2 }, { id: 'm3', quantity: 1 }]
}

export function storeOrderItem(userId, mealId, quantity, token) {
  return axios.put(
    `${FIREBASE_DB_URL}/orders/${userId}/${mealId}.json?auth=${token}`,
    JSON.stringify(quantity),
    { headers: { "Content-Type": "application/json" } }
  );
}

export function deleteOrderItem(userId, mealId, token) {
  return axios.delete(
    `${FIREBASE_DB_URL}/orders/${userId}/${mealId}.json?auth=${token}`
  );
}

export function clearOrder(userId, token) {
  return axios.delete(`${FIREBASE_DB_URL}/orders/${userId}.json?auth=${token}`);
}

// Placed orders (order history) are stored in Firebase like this:
// placedOrders: {
//   <userId>: {
//     <orderId>: {            // orderId is generated by Firebase (POST)
//       createdAt: "2026-10-06T10:15:00.000Z",
//       items: { <mealId>: <quantity>, <mealId>: <quantity> }
//     }
//   }
// }

export async function fetchPlacedOrders(userId, token) {
  const response = await axios.get(
    `${FIREBASE_DB_URL}/placedOrders/${userId}.json?auth=${token}`
  );

  const ordersObj = response.data || {};
  return Object.keys(ordersObj)
    .map((orderId) => {
      const itemsObj = ordersObj[orderId].items || {};
      return {
        id: orderId,
        createdAt: ordersObj[orderId].createdAt,
        items: Object.keys(itemsObj).map((mealId) => ({
          id: mealId,
          quantity: itemsObj[mealId],
        })),
      };
    })
    .sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt)); // newest first
}

// returns the id that Firebase generated for the new order
export async function storePlacedOrder(userId, order, token) {
  const response = await axios.post(
    `${FIREBASE_DB_URL}/placedOrders/${userId}.json?auth=${token}`,
    JSON.stringify(order),
    { headers: { "Content-Type": "application/json" } }
  );
  return response.data.name;
}